### ISSUE TITLE
Testing pivot_table in v1.1.1-dev302 (preparation for v1.1.1) show test is not deterministic

### ISSUE THREAD

**Issue by carlopi** [Alex-Monahan/pivot_table#1]
I triggered a round of tests on DuckDB's community extensions, and there is a failure on MacOS run (but not on the linux one ??) for `pivot_table`.

See here: https://github.com/duckdb/community-extensions/actions/runs/10973205947/job/30470351815#step:17:102.

Unsure if this needs to be solved at the implementation level or adding a `rowsort` attribute to the test results.

**Comment by Alex-Monahan** [comment]
Oh, I think I fixed this on main. I'll update the commit sha!

**Comment by carlopi** [comment]
Actually I am not sure, it might also be a problem in DuckDB somewhere, even though I can see where this would come from.

**Comment by Alex-Monahan** [comment]
It was a logical miss on my part! I needed to add one more column to the order by in some specific cases. That has been fixed, so CI is running again now with a new SHA!

**Comment by carlopi** [comment]
I think this works as expected, thanks!
